spring:
  application:
    name: sapp
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:./db_dev
      driverClassName: org.h2.Driver
      username: sa
      password:
server:
  port: 8015